[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "utsav-dhimmar", email = "utsavdhimmar987@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "elasticsearch[async]>=9.5.0",
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
backend = "app.main:main"

# [build-system]
# requires = ["uv_build>=0.12.0,<0.13.0"]
# build-backend = "uv_build"
